PENDING = "Pending"
PROCESSING = "Processing"
SHIPPED = "Shipped"
DELIVERED = "Delivered"
CANCELLED = "Cancelled"
RETURNED = "Returned"

ORDER_STATUS_CHOICES = (
    (PENDING, PENDING),
    (PROCESSING, PROCESSING),
    (SHIPPED, SHIPPED),
    (DELIVERED, DELIVERED),
    (CANCELLED, CANCELLED),
    (RETURNED, RETURNED),
)